Repository ColmeiaUDESC/site-colmeia, pull requests merged in 2021-07, with the labels that each got.

#28 Solução do erro do docker + postgres (Documentação)
  docs.md
Labels: bug

#46 estilização do dashboard/dashboard funcional
  app/controllers/dashboard_controller.rb
  app/controllers/posts_controller.rb
  app/helpers/application_helper.rb
  app/javascript/packs/sidebar.js
  app/views/dashboard/edit_post.html.erb
  app/views/dashboard/index.html.erb
  app/views/dashboard/list_posts.html.erb
  app/views/dashboard/list_users.html.erb
  app/views/dashboard/new_post.html.erb
  app/views/layouts/dashboard.html.erb
  app/views/posts/_form.html.erb
  app/views/shared/_dashboard_sidebar.html.erb
  app/views/shared/_navbar.html.erb
  config/routes.rb
  db/schema.rb
Labels: html-css, rails, tailwind-css

#78 Add campo situação na edição de usuário no dash
  app/controllers/user_controller.rb
Labels: rails
